# Generated by Django 3.1.7 on 2021-03-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistentry',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
